# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    controller:
        redirect_response_code: 302
    driver: "gd"
    webp:
        generate: true
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                # thumbnail: { size: [223, 223], mode: inset }
                # background: { size: [124, 94], position: center, color: '#000000' }
            # post_processors:
                # cwebp: { metadata: 'none', q: 70 }
                # mozjpeg: { quality: 70 }
                # jpegoptim: { strip_all: true, max: 70, progressive: true }
                # optipng: { strip_all: true, level: 5 }
                # pngquant: { quality: "75-85" }
