controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

PageNotFound:
    path: 
        - /{path}
        - /{path}/{id}
        - profil/{path}
        - profil/{id}/{path}
    controller: App\Controller\PageNotFoundController::PageNotFoundAction 
        

